### ISSUE TITLE
Problema com a inclusão da entrada @ABNT-option no arquivo referencias.bib

### ISSUE THREAD

**Issue by grazikirchner** [abntex/trabalho-academico-limarka#19]
Durante a compilação de um documento com o limarka, após a inclusão de uma entrada @ABNT-option (ver seção 8.1 em http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/abntex2/doc/abntex2cite.pdf) no arquivo referencias.bib, é gerado o seguinte erro:

~/limarka/conversor.rb:141: in `block in cria_xxx_referencias': undefined method ìnclude? ' for nil:NILClass (NoMethodError).
(...)

Parece-me que o erro é devido ao limarka não esperar uma entrada deste tipo no arquivo referencias.bib

**Comment by edusantana** [comment]
Esse problema do limarka e não do template, cadastrei o bug em https://github.com/abntex/limarka/issues/150
