### ISSUE TITLE
Fonte de capítulo e do texto estão diferentes

### ISSUE THREAD

**Issue by cauachagas** [abntex/trabalho-academico-limarka#25]
# Modelo Atual

Como reportado pelo [RaulMendes94](https://github.com/RaulMendes94) no [chat do Limarka](https://gitter.im/abntex/limarka), as fontes da capa e texto se diferem, como visto abaixo

![Monografia-projeto](https://user-images.githubusercontent.com/26585248/60063350-07860400-96d3-11e9-85ca-56a6e95713af.png)

Uma simples solução é adicionar 
```latex
\renewcommand{\ABNTEXchapterfont}{\normalfont}
```
Após a seleção da fonte. 

Para fonte Arial funcional com `pdflatex`: 
```latex
\usepackage[scaled]{helvet} % Usa a fonte helvet
\renewcommand\familydefault{\sfdefault} 
```

# Solução mais completa

Uma solução mais completa, que primeira tenta usar fontes com `XeLaTeX`, e se não existir, usará `pdfLaTex`:

```latex
\usepackage{ifxetex}
\ifxetex
  \usepackage{fontspec}
  \defaultfontfeatures{Ligatures={TeX}}
  \setmainfont{Times New Roman}
\else % pdflatex
  \usepackage{times}			% Usa a fonte times
  \usepackage[T1]{fontenc}		% Selecao de codigos de fonte.
  \usepackage[utf8]{inputenc}	% Codificacao do documento (conversão automática dos acentos)
\fi
\renewcommand{\ABNTEXchapterfont}{\normalfont}
```

O resultado:
![xxx-Monografia-projeto](https://user-images.githubusercontent.com/26585248/60063580-d4904000-96d3-11e9-9874-33586f20f992.png)

**Comment by edusantana** [comment]
No commit, você pode escrever `closes #25`, daí commit ele já fecha automaticamente este issue.

@cauachagas eu aprecio as duas contribuições, eu não me sinto "dono" do limarka, ele é da comunidade.

**Comment by cauachagas** [comment]
Obrigado pelo dica com o `closes`. 
Eu envie como uma PR porque mexerá com a estética do texto, que sempre usou a mesma formatação da abnTeX2 (mistura fontes serifada e não serifada) desde o início. Aliás, nunca entendi esse "estilo" do abnTeX2, já que a ABNT recomenda usar somente fonte única em todo o texto (Arial ou Times).
