### ISSUE TITLE
Incluir geração de gráficos do R

### ISSUE THREAD

**Issue by edusantana** [abntex/trabalho-academico-limarka#30]
Ver exemplos de gráficos:

- https://github.com/ufpb-computacao/estatistica-livro/tree/master/livro/images/densidades
- https://github.com/ufpb-computacao/estatistica-livro/tree/master/livro/images

[Tarefa Rake](https://github.com/ufpb-computacao/estatistica-livro/blob/44ea4dee263c48fc919713fe914d674759a87328/Rakefile#L227-L235):

```ruby
FileList['livro/images/**/*.R'].each do |source|
  rpdf = source.ext('pdf')
  file rpdf => source do |t|
    rm_rf "Rplots.pdf"
    sh "R --no-save < #{t.source}"
    mv "Rplots.pdf","#{t.name}"
  end
  task :r => rpdf
end
```

**Comment by edusantana** [comment]
Enquanto [guard.rake não gera uma nova versão](https://github.com/rubyist/guard-rake/pull/47), estou adotando uma [solução temporária no Rakefile](https://github.com/abntex/trabalho-academico-limarka/blob/f33f36dea5b7a74cd10a64c1eed3159c36f50bae/Rakefile#L20-L31), baseada [neste código](https://gist.github.com/edusantana/9aa2be37cf1f3d3cf04158260b5eba82)

**Comment by ipassos** [comment]
O seguinte código gera imagem com dois gráficos e retira as margens do arquivo `pdf` final. Conforme:
 * http://ecologia.ib.usp.br/bie5782/doku.php?id=bie5782:03_apostila:05a-graficos
 * https://www.datamentor.io/r-programming/subplot/

```R
library(grDevices)
pdf(width =10, height = 6)
par(mfrow = c(1,2), mai = c(0, 0, 0, 0))
x = c(10,20,3,4,15,32,11,12,33,5,10,2,33,22,11,22,7)
y = c(3,1,3,4,5,6,7,8,9,23,15,18,45,32,43,65,19)
par(fig=c(0.05,0.5,0,1))
hist(x,ylab=expression(F[i]),xlab="Classes",main="")
par(fig=c(0.55,1,0,1), new=TRUE)
plot(x,y)
dev.off()
```

**Comment by ipassos** [comment]
* A função `pdf()` do pacote `grDevices` (encerrada pela função  `dev.off()`) permite alterar configurações da imagem final no pdf gerado. 

* A primeira função `par()` configura a matriz de gráficos (`mfrow`) e as margens da imagem final (`mai`ou `mar`). As outras duas configuram a área que cada um dos gráficos (`fig`) ocupa na figura. A partir do segundo gráfico necessita do argumento `new = TRUE` para que cada novo gráfico seja sobreposto na mesma imagem.

**Comment by ipassos** [comment]
O `pdf` final da imagem não tem mais margem. Porém no arquivo final do trabalho (`.md`) ainda tem.

**Comment by edusantana** [comment]
Eu criei o arquivo [imagens/R/dois-graficos.R](https://github.com/abntex/trabalho-academico-limarka/blob/master/imagens/R/dois-graficos.R) com o seu código. Eu achei que ficou muito bom, o espaçamento está aceitável (entre as legendas e o gráfico), *não acha*?

![Captura de tela de 2020-07-15 20-15-08](https://user-images.githubusercontent.com/3603111/87609055-e924e900-c6d7-11ea-98c1-688d9d0c71a5.png)

- [x] Possibilitar incluir gráficos R no limarka
- [x] Documentar [uso do R](https://github.com/abntex/limarka/wiki/Para-usu%C3%A1rios-do-R)

Conforme conversamos, lembro que agora você precisaria gerar os gráficos (que antes eram gerados no servidor) na máquina local, mas você disse que isso não era problema. Então pergunto, está necessitando de mais alguma atualização para a sua dissertação?
